server:
  port: 8085

spring:
  application:
    name: cart-service

  datasource:
    url: ${CART_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5436/cart_service_db}
    username: ${CART_SERVICE_DB_USERNAME:cart_service_user}
    password: ${CART_SERVICE_DB_PASSWORD:cart_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: cart-service-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cache:
    type: redis
    redis:
      time-to-live: 5m
      cache-null-values: false

  redis:
    host: cart-service-cache
    port: 6379
    timeout: 2000

kafka:
  topic:
    orderConfirmed: order.order.confirmed


catalog:
  service:
    url: "http://catalog-service:8083"


logging:
  level:
    org.springframework.cache: DEBUG
    org.springframework.cache.interceptor: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG